### ISSUE TITLE
variable_names_map for PET in bmi_c_cfe module 

### ISSUE THREAD

**Issue by towlere** [mines-ciroh/clear_creek_demo#5]
Is there a reason that in the bmi_c_cfe module of the realization_file.06719505.cfe.json for "variables_name_map" has 
"water_potential_evaporation_flux": "potential_evapotranspiration",
https://github.com/mines-ciroh/clear_creek_demo/blob/cdfe25c49eb66e9b697da3a56be4a8c2092cc5ac/config/06719505/realization_file.06719505.cfe.json#L57

while in the bmi_c_cfe module of the realization_file.06719505.nom.json for "variables_name_map" has
"water_potential_evaporation_flux": "water_potential_evaporation_flux",
https://github.com/mines-ciroh/clear_creek_demo/blob/cdfe25c49eb66e9b697da3a56be4a8c2092cc5ac/config/06719505/realization_file.06719505.nom.json#L78C37-L78C108

**Comment by andywood** [comment]
I'm not sure -- but I think noah-om doesn't use pet as an input forcing so this setting may have been left at a default.  For cfe (which I think does use it?), it would use the name of the actual pet module output.

**Comment by joshsturtevant** [comment]
@towlere - Good eye, I copied this OWP[ realization file ](https://github.com/NOAA-OWP/ngen/blob/master/data/test_bmi_multi_realization_config_w_noah_pet_cfe.json), but looking at it again, I do wonder if this is an error, since the PET module is actually outputting `water_potential_evaporation_flux`. Fixed in [this commit](https://github.com/mines-ciroh/clear_creek_demo/commit/9ab2703f2bdcff148e48a47efb7b1259f7bc50d8).
